//! AXP2101 telemetry for the Waveshare ESP32-S3 Touch AMOLED 2.16.
//!
//! The AXP2101 shares the board's I2C bus with the CST9220 touch controller.
//! Unlike the M5Stack Core2, display brightness is not supplied by a PMIC LDO:
//! it is controlled by the CO5300's `0x51` command. This module deliberately
//! avoids changing board-specific power rails. Charging is configured for
//! the installed 1000mAh, 4.2V cell at 500mA (0.5C).

use axp2101_dd::{AdcChannel, Axp2101Async, AxpError, AxpInterface};

/// A power-key gesture classified and latched by the AXP2101.
#[derive(Clone, Copy, Debug, PartialEq, Eq, defmt::Format)]
pub enum PowerKey {
    /// The PWR button was released before the long-press threshold.
    Short,
    /// The PWR button was held past the configured 2.5 second threshold.
    Long,
}

#[derive(Clone, Copy, Debug, Default, defmt::Format)]
pub struct PmicStats {
    pub battery_mv: u16,
    pub vbus_mv: u16,
    pub vsys_mv: u16,
    pub temperature_c: f32,
    pub state_of_charge: u8,
    pub battery_present: bool,
    pub charging: bool,
    pub vbus_good: bool,
}

pub async fn init<I2C, E>(i2c: I2C) -> Result<Axp2101Async<AxpInterface<I2C>, E>, AxpError<E>>
where
    I2C: embedded_hal_async::i2c::I2c<Error = E>,
    E: core::fmt::Debug,
{
    let mut axp = Axp2101Async::new(i2c);

    // Verify that the expected PMIC responds before changing any registers.
    let chip_id = axp.get_chip_id().await?;
    defmt::info!("AXP2101 chip ID: 0x{:02X}", chip_id);
    if chip_id != 0x4a && chip_id != 0x47 {
        defmt::warn!("Unexpected AXP2101 chip ID: 0x{:02X}", chip_id);
    }

    // Apply the installed cell's charging policy on every boot, including after
    // a PMIC power cycle. Leave precharge, termination and protections intact.
    axp.set_battery_charge_voltage(axp2101_dd::ChargeVoltageLimit::V42)
        .await?;
    axp.set_battery_charge_current(axp2101_dd::FastChargeCurrentLimit::Ma500)
        .await?;

    // Read back the applied limits; other settings may survive an MCU reset.
    let charge = axp.ll.fast_charge_current_config().read_async().await?;
    let precharge = axp.ll.precharge_current_config().read_async().await?;
    let voltage = axp.ll.charge_voltage_config().read_async().await?;
    let input = axp.ll.input_current_limit().read_async().await?;
    let vindpm = axp.ll.vindpm_config().read_async().await?;
    let thermal = axp.ll.thermal_regulation_threshold().read_async().await?;
    defmt::info!(
        "AXP2101 charge limits: CC={} precharge={} voltage={} input={} VINDPM={} thermal={}",
        charge.fast_charge_current(),
        precharge.precharge_current(),
        voltage.charge_voltage(),
        input.current_limit(),
        vindpm.vindpm_threshold(),
        thermal.tregu_thld(),
    );
    let power = axp.ll.power_status().read_async().await?;
    let system = axp.ll.system_status().read_async().await?;
    let jeita = axp.ll.jeita_enable().read_async().await?;
    defmt::info!(
        "AXP2101 charge status: phase={} thermal-limited={} input-limited={} VINDPM-active={} JEITA={}",
        system.charging_status(),
        power.thermal_regulation_active(),
        power.current_limit_active(),
        system.vindpm_active(),
        jeita.jeita_en(),
    );

    // Require a two-second hold to power on from the PMIC's off state, report
    // a long press after 2.5 seconds while running, and retain a 10-second
    // PMIC-controlled emergency power-off. These fields do not affect the
    // board's regulators.
    axp.ll
        .power_on_level()
        .modify_async(|register| {
            register.set_on_level(axp2101_dd::OnLevel::S2);
            register.set_off_level(axp2101_dd::OffLevel::S10);
            register.set_irq_level(axp2101_dd::IrqLevel::S25);
        })
        .await?;

    // The official Waveshare ESP-IDF example enables both power-key events.
    // We poll their latched status bits because the PMIC IRQ output is not
    // exposed as a dedicated MCU GPIO on this board.
    axp.ll
        .irq_enable_1()
        .modify_async(|register| {
            register.set_power_key_short_press_irq_enable(true);
            register.set_power_key_long_press_irq_enable(true);
        })
        .await?;

    // Discard the event generated by the press that powered the board on.
    axp.ll
        .irq_status_1()
        .write_async(|register| {
            register.set_pons_irq(true);
            register.set_ponl_irq(true);
            register.set_ponn_irq(true);
            register.set_ponp_irq(true);
        })
        .await?;

    axp.ll
        .battery_detection_control()
        .modify_async(|register| register.set_bat_det_en(true))
        .await?;

    for channel in [
        AdcChannel::BatteryVoltage,
        AdcChannel::VbusVoltage,
        AdcChannel::VsysVoltage,
        AdcChannel::DieTemperature,
    ] {
        axp.set_adc_channel_enable(channel, true).await?;
    }

    Ok(axp)
}

/// Return and clear a latched PWR-button gesture.
///
/// A long press takes precedence if both status bits are present.
pub async fn poll_power_key<I2C, E>(
    axp: &mut Axp2101Async<AxpInterface<I2C>, E>,
) -> Result<Option<PowerKey>, AxpError<E>>
where
    I2C: embedded_hal_async::i2c::I2c<Error = E>,
    E: core::fmt::Debug,
{
    let status = axp.ll.irq_status_1().read_async().await?;
    let long = status.ponl_irq();
    let short = status.pons_irq();
    if !long && !short {
        return Ok(None);
    }

    axp.ll
        .irq_status_1()
        .write_async(|register| {
            if long {
                register.set_ponl_irq(true);
            }
            if short {
                register.set_pons_irq(true);
            }
        })
        .await?;

    Ok(Some(if long {
        PowerKey::Long
    } else {
        PowerKey::Short
    }))
}

pub async fn read_stats<I2C, E>(
    axp: &mut Axp2101Async<AxpInterface<I2C>, E>,
) -> Result<PmicStats, AxpError<E>>
where
    I2C: embedded_hal_async::i2c::I2c<Error = E>,
    E: core::fmt::Debug,
{
    let battery_present = axp.is_battery_present().await?;
    let vbus_good = axp.is_vbus_good().await?;

    Ok(PmicStats {
        battery_mv: if battery_present {
            axp.get_battery_voltage_mv().await?
        } else {
            0
        },
        vbus_mv: if vbus_good {
            axp.get_vbus_voltage_mv().await?
        } else {
            0
        },
        vsys_mv: axp.get_vsys_voltage_mv().await?,
        temperature_c: axp.get_die_temperature_c().await?,
        state_of_charge: if battery_present {
            axp.get_battery_level().await?
        } else {
            0
        },
        battery_present,
        charging: axp.is_charging().await?,
        vbus_good,
    })
}
